# Dependencies
markdown:         kramdown
kramdown:
  parse_block_html: true 
highlighter:      rouge

# Permalinks
permalink:  /:categories/:year/:month/:day/:title
paginate_path:  /SFS_GIS_R_training/page:num

# Setup
title:            'R Spatial Workshop for 2018 AWRA GIS Conference'
tagline:          ''
description:      'This material is for a workshop at the 2018 AWRA GIS
                  conference in Orlando, FL, April 2018.'
url:              http://mhweber.github.io/AWRA_GIS_R_Workshop
baseurl:          /SFS_GIS_R_training

#author:
#  name:           ''
#  url:            http://ryan-hill.github.io

paginate:         15

timezone:         America/Los_Angeles

#Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

plugins:
  - jekyll-seo-tag

# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

auto: true # automatically update your jekyll
server: true # runs a local server
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

